language: python
python:
  # - "2.7" Removed because of Python 2 urllib.parse ImportError
  # https://github.com/necaris/python-openid/commit/53ec8b0eeb28ed19220df2577b429168698d96e4
  - "3.4"
  - "3.5"
before_install:
  - pip install -r requirements.txt
install:
  - pip install coveralls
script:
  - coverage run manage.py test
after_success:
  - coveralls
branches:
  only:
    - develop