# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 04:54
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthUsersocialauth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=255)),
                ('extra_data', models.TextField()),
            ],
            options={
                'db_table': 'social_auth_usersocialauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('effect_id', models.AutoField(primary_key=True, serialize=False)),
                ('effect_name', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=50)),
                ('path', models.ImageField(upload_to=app.models.effects_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(upload_to='/photo/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEdit',
            fields=[
                ('photo_edit_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload', models.ImageField(upload_to='/edits/')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Photo')),
            ],
        ),
    ]
