# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='photoedit',
            name='upload',
            field=models.ImageField(upload_to='edits/'),
        ),
    ]
