# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_use_ImageField'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('effect_id', models.AutoField(primary_key=True, serialize=False)),
                ('effect_name', models.CharField(max_length=20)),
                ('path', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
