# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 06:28
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_CreateEffectsModel'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 7, 6, 28, 44, 264097, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='effects',
            name='path',
            field=models.ImageField(upload_to=app.models.effects_file_name),
        ),
    ]
