# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_AddDateTimeField'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effects',
            name='date_added',
        ),
        migrations.AddField(
            model_name='effects',
            name='file_name',
            field=models.CharField(default='sint', max_length=50),
        ),
    ]
